import Head from "next/head";
import styled from "styled-components";
import tw from "twin.macro";
import Homepage from "../containers/Homepage";

const AppContainer = styled.div`
  ${tw`
  flex
  w-full 
  h-full
  items-center`}
`;
export default function Home() {
  return (
    <AppContainer>
      <Head>
        <title>Skilzen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage />
    </AppContainer>
  );
}
